REM -------------------------------------------------------
REM -- Put keyboard codes (xx) and                       --
REM -- code page variables (yyy) here.                   --
REM -------------------------------------------------------

REM MODE CON CP PREP=((yyy) EGA.CPI)
REM MODE CON CP SEL=yyy
REM KEYB xx,yyy


REM -------------------------------------------------------
REM -- Put network or CD-ROM drivers here.               --
REM -------------------------------------------------------

REM Windows DOS:
REM MSCDEX.EXE /D:driver_name [/L:drive_letter] [/M:buffers]

REM Caldera DOS:
REM NWCDEX.EXE /D:driver_name [/L:drive_letter] [/M:buffers]